spring:
  application:
    name: registry-service-sba
  boot:
    admin:
      client:
        url: http://spring-admin-ct.lab.pl/
        instance: ${HOSTNAME}
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://spring-config-ct.lab.pl/}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

logging:
  level:
    com:
      netflix:
        eureka: INFO
        discovery: INFO


