spring:
  application:
    name: registry-service-sba
  boot:
    admin:
      client:
        url: http://spring-admin.lab.pl
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://spring-config.lab.pl/}


management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

eureka:
  instance:
    hostname: $(HOSTNAME)
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    com:
      netflix:
        eureka: INFO
        discovery: INFO


