server:
  port: 8761

spring:
  application:
    name: registry-service-sba
  boot:
    admin:
      client:
        url: http://spring-admin-service/
        instance:
          name: spring-registry-sba
          prefer-ip: true

eureka:
  client:
    registry-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

logging:
  level:
    com:
      netflix:
        eureka: INFO
        discovery: INFO


