spring:
  application:
    name: registry-service
  boot:
    admin:
      client:
        url: http://localhost:8762
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}


management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    com:
      netflix:
        eureka: INFO
        discovery: INFO


