server:
  port: 8761

spring:
  application:
    name: registry-service-sba
  boot:
    admin:
      client:
        url: http://spring-admin-service.default.svc.cluster
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://spring-config-service.default.svc.cluster.local}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

logging:
  level:
    com:
      netflix:
        eureka: INFO
        discovery: INFO


